### ISSUE TITLE
the datasets

### ISSUE THREAD

**Issue by Reenie17** [smu-ivpl/FastInterCU-VVC#1]
hello friend, I have some questions about the datasets. I downloaded your datasets, but they are all black pictures. Is there anything wrong with the datasets. Looking forward to your reply,thank you!

**Comment by tengqi200** [comment]
> hello friend, I have some questions about the datasets. I downloaded your datasets, but they are all black pictures. Is there anything wrong with the datasets. Looking forward to your reply,thank you!

I believe the pictures in this dataset are OK and the bit depth of these pictures is 10-bit. 
You can view the 10-bit picture in Matlab. Using "imshow(img, [0 1023])".

**Comment by unacanal** [comment]
> hello friend, I have some questions about the datasets. I downloaded your datasets, but they are all black pictures. Is there anything wrong with the datasets. Looking forward to your reply,thank you!

Sorry for late response. As @tengqi200 said, the pictures are 10-bit.
